### ISSUE TITLE
对于代码的疑问

### ISSUE THREAD

**Issue by michealowen** [sazima/gps_kalman_filter#1]
您好，我看了您的代码和您README里的引用，我认为实际上用的并不是卡尔曼滤波，只是简单使用速度对位置的修正。

**Comment by fff2zrx** [comment]
我也觉得不是卡尔曼滤波或者说写错了，真实值与预测值的协方差更新怎么会是再加上时长乘以速度的平方，还除以了1000，
`self.variance += duration * speed * speed / Decimal('1000')`
而且位置更新没有利用速度信息

**Comment by fff2zrx** [comment]
> 您好，我看了您的代码和您README里的引用，我认为实际上用的并不是卡尔曼滤波，只是简单使用速度对位置的修正。

我也觉得不是卡尔曼滤波或者说写错了，真实值与预测值的协方差更新怎么会是再加上时长乘以速度的平方，还除以了1000，
self.variance += duration * speed * speed / Decimal('1000')
而且位置更新没有利用速度信息

**Comment by sazima** [comment]
@michealowen  @fff2zrx  
从我的项目中看, 这段代码确实让人的轨迹变得更接近真实且平滑了.  我不是这方面的专家, 不太清楚是不是kalman, 你看下这个是否可以帮助到你.
 https://stackoverflow.com/questions/1134579/smooth-gps-data

**Comment by michealowen** [comment]
> @michealowen @fff2zrx
> 从我的项目中看, 这段代码确实让人的轨迹变得更接近真实且平滑了. 我不是这方面的专家, 不太清楚是不是kalman, 你看下这个是否可以帮助到你.
> https://stackoverflow.com/questions/1134579/smooth-gps-data

轨迹平滑的原因我觉得是因为那个利用他的公式得到的 k 会随着速度明显变化，从而导致平滑

**Comment by michealowen** [comment]
> > 您好，我看了您的代码和您README里的引用，我认为实际上用的并不是卡尔曼滤波，只是简单使用速度对位置的修正。
> 
> 我也觉得不是卡尔曼滤波或者说写错了，真实值与预测值的协方差更新怎么会是再加上时长乘以速度的平方，还除以了1000，
> self.variance += duration * speed * speed / Decimal('1000')
> 而且位置更新没有利用速度信息



> > 您好，我看了您的代码和您README里的引用，我认为实际上用的并不是卡尔曼滤波，只是简单使用速度对位置的修正。
> 
> 我也觉得不是卡尔曼滤波或者说写错了，真实值与预测值的协方差更新怎么会是再加上时长乘以速度的平方，还除以了1000，
> self.variance += duration * speed * speed / Decimal('1000')
> 而且位置更新没有利用速度信息

我使用了卡尔曼滤波做轨迹曲线拟合，但是现在效果不太好，可以和您交流一下么

**Comment by fff2zrx** [comment]
> @michealowen @fff2zrx
> 从我的项目中看, 这段代码确实让人的轨迹变得更接近真实且平滑了. 我不是这方面的专家, 不太清楚是不是kalman, 你看下这个是否可以帮助到你.
> https://stackoverflow.com/questions/1134579/smooth-gps-data

好的感谢，我也是最近学这个，看到了您的项目感觉跟我看的理论不太一样

**Comment by fff2zrx** [comment]
> > > 您好，我看了您的代码和您README里的引用，我认为实际上用的并不是卡尔曼滤波，只是简单使用速度对位置的修正。
> > 
> > 
> > 我也觉得不是卡尔曼滤波或者说写错了，真实值与预测值的协方差更新怎么会是再加上时长乘以速度的平方，还除以了1000，
> > self.variance += duration * speed * speed / Decimal('1000')
> > 而且位置更新没有利用速度信息
> 
> > > 您好，我看了您的代码和您README里的引用，我认为实际上用的并不是卡尔曼滤波，只是简单使用速度对位置的修正。
> > 
> > 
> > 我也觉得不是卡尔曼滤波或者说写错了，真实值与预测值的协方差更新怎么会是再加上时长乘以速度的平方，还除以了1000，
> > self.variance += duration * speed * speed / Decimal('1000')
> > 而且位置更新没有利用速度信息
> 
> 我使用了卡尔曼滤波做轨迹曲线拟合，但是现在效果不太好，可以和您交流一下么

我也是在学，可以加我QQ1324802616交流
